# Generated by Django 3.1.5 on 2021-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/profile/images', verbose_name='تصویر'),
        ),
    ]
