# Generated by Django 3.1.5 on 2021-01-10 16:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم شهر')),
                ('slug', models.SlugField(max_length=30, verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('pic', models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/images', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام جایگزین')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گالری تصاویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.category', verbose_name='فرزند')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان آکهی')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='قیمت')),
                ('pic', models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/product/images', verbose_name='تصویر')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='شماره تماس', max_length=31)),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('category', models.ManyToManyField(blank=True, to='app.Category', verbose_name='دسته بندی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('image_gallery', models.ManyToManyField(blank=True, to='app.ImageGallery', verbose_name='گالری تصاویر')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
    ]
