# Generated by Django 3.1.5 on 2021-01-22 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, blank=True, max_length=30, null=True, unique=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان آکهی')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='قیمت')),
                ('pic', models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/product/images', verbose_name='تصویر')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('video', models.FileField(blank=True, upload_to='upload/product/video', verbose_name='ویدئو')),
                ('is_active_comment', models.BooleanField(blank=True, default=False, verbose_name='فعال کردن نظرات')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
                'ordering': ('-publish_date',),
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم شهر')),
                ('slug', models.SlugField(max_length=30, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, upload_to='media/city/', verbose_name='تصویر شهر')),
                ('fav', models.BooleanField(blank=True, default=False, verbose_name='محبوب')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('pic', models.ImageField(default='upload/images/no-img.jpg', upload_to='upload/images', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام جایگزین')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گالری تصاویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='نظر')),
                ('reply', models.TextField(blank=True, max_length=500, null=True, verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_reply', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advertise', verbose_name='آگهی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, upload_to='media/cat/', verbose_name='تصویر دسته')),
                ('fav', models.BooleanField(blank=True, default=False, verbose_name='محبوب')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='آیکون')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.category', verbose_name='فرزند')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='advertise',
            name='category',
            field=models.ManyToManyField(blank=True, to='app.Category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='image_gallery',
            field=models.ManyToManyField(blank=True, to='app.ImageGallery', verbose_name='گالری تصاویر'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
