# Generated by Django 3.1.5 on 2021-01-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field=280, upload_to='media/city/', verbose_name='تصویر شهر', width_field=350),
        ),
    ]
