# Generated by Django 3.1.5 on 2021-01-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210117_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/city/', verbose_name='تصویر شهر'),
        ),
    ]
