# Generated by Django 3.1.5 on 2021-01-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210118_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=20, verbose_name='آیکون'),
        ),
    ]
