# Generated by Django 3.1.5 on 2021-01-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_advertise_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='is_active_comment',
            field=models.BooleanField(blank=True, default=False, verbose_name='فعال کردن نظرات'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, max_length=30, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='اسلاگ'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('comment', models.TextField(max_length=500, verbose_name='نظر')),
                ('reply', models.TextField(blank=True, max_length=500, null=True, verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_reply', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advertise', verbose_name='آگهی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
