# Generated by Django 3.1.5 on 2021-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210119_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='is_active_comment',
            field=models.BooleanField(blank=True, default=True, verbose_name='فعال کردن نظرات'),
        ),
    ]
