# Generated by Django 3.1.5 on 2021-01-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210119_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertise',
            options={'ordering': ('-publish_date',), 'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی ها'},
        ),
    ]
